# Generated by Django 5.2.6 on 2025-09-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='button1_url',
            new_name='download_button_link',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='button2_url',
            new_name='learn_more_button_link',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button1_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='button2_text',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='title',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='video',
        ),
        migrations.AddField(
            model_name='herosection',
            name='background_video',
            field=models.FileField(blank=True, null=True, upload_to='hero_videos/'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description',
            field=models.TextField(default='Access top-quality tutorials tailored for Nigerian university students. Learn at your own pace, anytime, anywhere with our comprehensive learning platform.'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='download_button_text',
            field=models.CharField(default='Download Now', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='learn_more_button_text',
            field=models.CharField(default='Learn More', max_length=50),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_gradient',
            field=models.CharField(default='Academic Potential', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_main',
            field=models.CharField(default='Unlock Your', max_length=200),
        ),
        migrations.AddField(
            model_name='herosection',
            name='title_sub',
            field=models.CharField(default="with Proffyemphy's Ideal Academy", max_length=200),
        ),
    ]
