# Generated by Django 5.2.6 on 2025-09-07 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_statistic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('graduation-cap', 'Graduation Cap'), ('users', 'Users'), ('presentation', 'Presentation')], default='graduation-cap', max_length=50)),
                ('color_from', models.CharField(default='#34D399', max_length=7)),
                ('color_to', models.CharField(default='#10B981', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Stat',
        ),
        migrations.DeleteModel(
            name='WhyChooseUs',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='content',
        ),
        migrations.RemoveField(
            model_name='aboutsection',
            name='heading',
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='description',
            field=models.TextField(default="Proffyemphy's Ideal Academy is dedicated to providing comprehensive tutorial support to students across all Nigerian universities. Our platform offers a wide range of courses, expert instructors, and interactive learning tools to help you excel in your studies."),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_main',
            field=models.CharField(default='Empowering Nigerian Students', max_length=200),
        ),
        migrations.AddField(
            model_name='aboutsection',
            name='title_sub',
            field=models.CharField(default='to Excel Academically', max_length=200),
        ),
    ]
