# Generated by Django 5.2.6 on 2025-09-07 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_feature_statistics_delete_stat_delete_whychooseus_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Statistics',
            new_name='Aboutstat',
        ),
    ]
