# Generated by Django 5.2.6 on 2025-09-07 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_statistics_aboutstat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutor',
            old_name='image',
            new_name='photo',
        ),
        migrations.AlterField(
            model_name='tutor',
            name='course',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
