# Generated by Django 5.2.6 on 2025-09-07 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_image_tutor_photo_alter_tutor_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='role',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
