# Generated by Django 5.2.6 on 2025-09-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tutor_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='student_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='testimonial',
            name='image',
        ),
        migrations.AddField(
            model_name='testimonial',
            name='photo',
            field=models.ImageField(default='exit', upload_to='testimonials/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='university',
            field=models.CharField(max_length=100),
        ),
    ]
