# Generated by Django 5.2.6 on 2025-09-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_student_name_testimonial_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vision_title', models.CharField(default='Our Vision', max_length=100)),
                ('vision_text', models.TextField(default='To become Nigeria’s leading online academic platform, equipping every student with the right knowledge, tools, and guidance to achieve excellence and compete globally.')),
                ('mission_title', models.CharField(default='Our Mission', max_length=100)),
                ('mission_text', models.TextField(default='To provide accessible, affordable, and high-quality tutorial support that empowers Nigerian students to excel academically, fostering innovation, confidence, and lifelong learning.')),
            ],
        ),
    ]
