# Generated by Django 5.2.6 on 2025-09-07 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_visionmission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CTAFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_svg', models.TextField(help_text='Paste raw SVG code here')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CTASection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_text', models.CharField(default='Join the Success Story', max_length=100)),
                ('heading_main', models.CharField(default='Ready to Get', max_length=200)),
                ('heading_gradient', models.CharField(default='Started?', max_length=200)),
                ('subtext', models.TextField(default="Join thousands of students who are achieving academic success with Proffyemphy's Ideal Academy. Sign up today and start your learning journey towards excellence.")),
                ('button_text', models.CharField(default='Create Account Now', max_length=100)),
                ('button_url', models.URLField(default='#')),
            ],
        ),
    ]
