# Generated by Django 5.2.6 on 2025-09-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_ctafeature_ctasection'),
    ]

    operations = [
        migrations.CreateModel(
            name='DownloadAppFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('icon_svg', models.TextField(help_text='Paste raw SVG code here')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='DownloadAppSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading_main', models.CharField(default='Download the App', max_length=100)),
                ('heading_highlight', models.CharField(default='Today', max_length=100)),
                ('description', models.TextField(default="Access Proffyemphy's Ideal Academy on the go with our mobile app. Download now and start learning anytime, anywhere.")),
                ('button_text', models.CharField(default='Download App', max_length=50)),
                ('button_url', models.URLField(default='#')),
            ],
        ),
        migrations.DeleteModel(
            name='DownloadSection',
        ),
    ]
