# Generated by Django 5.2.6 on 2025-09-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_downloadappfeature_downloadappsection_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academy_name', models.CharField(default="Proffyemphy's Ideal Academy", max_length=255)),
                ('description', models.TextField(default='Empowering Nigerian university students with comprehensive tutorial support and expert guidance for academic excellence.')),
                ('email', models.EmailField(default='proffyemphy001@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+234 (0) 8128235805', max_length=50)),
                ('address', models.TextField(default='5, Okeolokun street, Ok bustop, Agura-gberigbe, Ikorodu, Lagos state')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='footer/')),
                ('facebook', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('tiktok', models.URLField(blank=True, null=True)),
                ('whatsapp', models.URLField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
