# Generated by Django 5.2.6 on 2025-09-07 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_footer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='icon',
        ),
        migrations.AddField(
            model_name='feature',
            name='svg_icon',
            field=models.TextField(default='exit', help_text='Paste the full SVG code here. Make sure to use double quotes for attributes.'),
            preserve_default=False,
        ),
    ]
